version: '3.8'

services:
  neo4j:
    image: neo4j:5.26.0
    container_name: metabolic-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-password123}
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - graphiti-network

  graphiti-mcp:
    image: zepai/knowledge-graph-mcp:latest
    container_name: metabolic-graphiti-mcp
    ports:
      - "8000:8000"  # SSE transport
    environment:
      # Neo4j 연결
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password123}
      
      # OpenAI API
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-gpt-4o-mini}
      - SMALL_MODEL_NAME=${SMALL_MODEL_NAME:-gpt-4o-mini}
      
      # LLM 설정
      - LLM_TEMPERATURE=${LLM_TEMPERATURE:-0.3}
      - SEMAPHORE_LIMIT=${SEMAPHORE_LIMIT:-10}
      
      # 텔레메트리 비활성화
      - GRAPHITI_TELEMETRY_ENABLED=false
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - graphiti-network

volumes:
  neo4j_data:
    driver: local

networks:
  graphiti-network:
    driver: bridge